### ISSUE TITLE
ValueError: could not convert string to float: '' while trying to run the example code for 'OMI NO2 Satellite -- OpenDAP to CMAQ-Grid'

### ISSUE THREAD

**Issue by bukim1** [barronh/cmaqsatproc#10]
Hi Barron, 

I tried to run your example code, 'OMI NO2 Satellite -- OpenDAP to CMAQ-Grid' 
https://github.com/barronh/cmaqsatproc?tab=readme-ov-file#omi-no2-satellite----opendap-to-cmaq-grid
but encountered 
ValueError: could not convert string to float: ''

The exception was raised at the line of
l3.to_netcdf(outpath)

Tracking back the origin, I found that it was caused by line 222 of xarray's code of conventions.py
result[...] = data

I printed some debug outputs and found that
the value of "data" is [0.0 1.0 2.0 3.0 4.0 5.0 6.0 7.0 8.0 9.0 10.0 11.0 12.0 13.0 14.0 15.0 16.0 17.0 18.0 19.0 20.0 21.0 22.0 23.0 24.0 25.0 26.0 27.0 28.0 29.0 30.0 31.0 32.0 33.0 '']
The shape of "data" is (35,).

Apparently, the last element of "data" caused the trouble.

FYI, the value of "name" is "layer" at the line 265 in conventions.py.

Let me know if you need more information from me.

**Comment by barronh** [comment]
Thanks for raising the issue. I think this bug was introduced in trying to add some additional metadata. It has been fixed it in version 0.4.0. 

Side note: In looking into this, I see that newer versions of pandas do not like the `stack` method. See associated #11

**Comment by barronh** [comment]
I verified the fix on my own server and on Google Colab using a fresh install. When you have confirmed the fix, please close this issue.

**Comment by bukim1** [comment]
Thank you, Barron. I am confirming that the issue is resolved.
