### ISSUE TITLE
Question regarding use of cmaqsatproc with opendap?

### ISSUE THREAD

**Issue by gc13141112** [barronh/cmaqsatproc#12]
I use the cmaqsatproc with opendap to process the tropomi data, but the following error occurred.
`11 ['https://tropomi.gesdisc.eosdis.nasa.gov/opendap/S5P_TROPOMI_Level2/S5P_L2__NO2____HiR.2/2019/182/S5P_RPRO_L2__NO2____20190701T001459_20190701T015629_08876_03_020400_20221105T194200.nc', 'https://tropomi.gesdisc.eosdis.nasa.gov/opendap/S5P_TROPOMI_Level2/S5P_L2__NO2____HiR.2/2019/182/S5P_RPRO_L2__NO2____20190701T015629_20190701T033758_08877_03_020400_20221105T194201.nc', 'https://tropomi.gesdisc.eosdis.nasa.gov/opendap/S5P_TROPOMI_Level2/S5P_L2__NO2____HiR.2/2019/182/S5P_RPRO_L2__NO2____20190701T033758_20190701T051928_08878_03_020400_20221105T194204.nc', 'https://tropomi.gesdisc.eosdis.nasa.gov/opendap/S5P_TROPOMI_Level2/S5P_L2__NO2____HiR.2/2019/182/S5P_RPRO_L2__NO2____20190701T051928_20190701T070058_08879_03_020400_20221105T194206.nc', 'https://tropomi.gesdisc.eosdis.nasa.gov/opendap/S5P_TROPOMI_Level2/S5P_L2__NO2____HiR.2/2019/182/S5P_RPRO_L2__NO2____20190701T070058_20190701T084228_08880_03_020400_20221105T194208.nc', 'https://tropomi.gesdisc.eosdis.nasa.gov/opendap/S5P_TROPOMI_Level2/S5P_L2__NO2____HiR.2/2019/182/S5P_RPRO_L2__NO2____20190701T084228_20190701T102357_08881_03_020400_20221105T194209.nc', 'https://tropomi.gesdisc.eosdis.nasa.gov/opendap/S5P_TROPOMI_Level2/S5P_L2__NO2____HiR.2/2019/182/S5P_RPRO_L2__NO2____20190701T152826_20190701T170956_08885_03_020400_20221105T194217.nc', 'https://tropomi.gesdisc.eosdis.nasa.gov/opendap/S5P_TROPOMI_Level2/S5P_L2__NO2____HiR.2/2019/182/S5P_RPRO_L2__NO2____20190701T170956_20190701T185126_08886_03_020400_20221105T194218.nc', 'https://tropomi.gesdisc.eosdis.nasa.gov/opendap/S5P_TROPOMI_Level2/S5P_L2__NO2____HiR.2/2019/182/S5P_RPRO_L2__NO2____20190701T185126_20190701T203256_08887_03_020400_20221105T194225.nc', 'https://tropomi.gesdisc.eosdis.nasa.gov/opendap/S5P_TROPOMI_Level2/S5P_L2__NO2____HiR.2/2019/182/S5P_RPRO_L2__NO2____20190701T203256_20190701T221425_08888_03_020400_20221105T194227.nc', 'https://tropomi.gesdisc.eosdis.nasa.gov/opendap/S5P_TROPOMI_Level2/S5P_L2__NO2____HiR.2/2019/182/S5P_RPRO_L2__NO2____20190701T221425_20190701T235555_08889_03_020400_20221105T194228.nc']
https://tropomi.gesdisc.eosdis.nasa.gov/opendap/S5P_TROPOMI_Level2/S5P_L2__NO2____HiR.2/2019/182/S5P_RPRO_L2__NO2____20190701T001459_20190701T015629_08876_03_020400_20221105T194200.nc
syntax error, unexpected WORD_WORD, expecting SCAN_ATTR or SCAN_DATASET or SCAN_ERROR
context: HTTP^ Basic: Access denied.
syntax error, unexpected WORD_WORD, expecting SCAN_ATTR or SCAN_DATASET or SCAN_ERROR
context: HTTP^ Basic: Access denied.
syntax error, unexpected WORD_WORD, expecting SCAN_ATTR or SCAN_DATASET or SCAN_ERROR
context: HTTP^ Basic: Access denied.
syntax error, unexpected WORD_WORD, expecting SCAN_ATTR or SCAN_DATASET or SCAN_ERROR
context: HTTP^ Basic: Access denied.
`

Thanks in advance for your help!

Chao

**Comment by barronh** [comment]
@gc13141112 

Take a look at the OpenDAP support section of the [README](https://github.com/barronh/cmaqsatproc?tab=readme-ov-file#opendap-support) file linked below and or the [OpenDAP setup example](https://barronh.github.io/cmaqsatproc/auto_examples/ex1_config_netrc.html)

**Comment by gc13141112** [comment]
Thx
