### ISSUE TITLE
AveragingKernel Calculation

### ISSUE THREAD

**Issue by barronh** [barronh/cmaqsatproc#4]
This issue is opened to address a new issue identified in #2 that is focused on OMPROFOZ averaging kernel. 

In issue #2, @chogrefe noted that when applying the averaging kernel cmaq2sat.py produced extremely small vertical column densities with OMNO2d even when the pure vertical column densities were large. This was the result of an incorrect AveragingKernel calculation, which would be very easy to make. Because it is such an easy mistake, it is being documented here.

cmaq2sat.py takes optional arguments `akpath` and `akkey`. Optionally, `akkey` can be provided as an expression that will be calculated in the context of a sat2cmaq.py L3 files. The averaging kernel, in this context, can be thought of as the relative weight that a partial vertical column density from the model should contribute to an satellite-like column (See Averaging Kernel Appendix).

The averaging kernel is calculated based on a 2D reported air mass factor (_M_) and a 3D scattering weight (_w_z_). cmaqsatproc uses an IOAPI-style output, which can only store 2D or 3D variables. To store the 2D air mass factor, we store "missing values" at all altitudes above the surface. So, any calculation of AveragingKernel should use the full 3D _w_z_, but only the first layer of _M_.

For OMNO2d, the scattering weights (_w_z_) is stored as ScatWgt and the Tropospheric Air Mass Factor (_M_) is stored as `AmfTrop`. Thus, it is wrong to use `ScatWgt[:] / AmfTrop[:]`, which would use masked aloft values and, therefore, create masked `AveragingKernel` above the OMI surface layer. Instead, you should use `ScatWgt[:] / AmfTrop[:, 0]` or `ScatWgt[:] / AmfTrop[:, [0]]`. The code below illustrates the point.

```
import numpy as np
np.set_printoptions(precision=2)

ScatWgt = np.array([[
    0.55, 0.58, 0.60, 0.63, 0.67, 1.36, 1.40, 1.47, 1.55, 1.62, 1.68, 1.75,
    1.83, 1.92, 2.01, 2.14, 2.26, 2.43, 2.60, 2.80, 2.98, 3.16, 3.35, 3.65,
    4.03, 4.47, 4.47, 4.28, 4.16, 4.07, 3.99, 3.89, 3.74, 3.60, 3.63
]], dtype='f')

AmfTrop = np.ma.masked_all_like(ScatWgt)
AmfTrop[0, 0] = 2.45

print('Bad', (ScatWgt / AmfTrop).filled(np.nan))
# Bad [[0.22  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan
#    nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan
#    nan  nan  nan  nan  nan  nan  nan]]

print('Good', (ScatWgt / AmfTrop[:, [0]]).filled(np.nan))
# Good [[0.22 0.24 0.24 0.26 0.27 0.56 0.57 0.6  0.63 0.66 0.69 0.71 0.75 0.78
#   0.82 0.87 0.92 0.99 1.06 1.14 1.22 1.29 1.37 1.49 1.64 1.82 1.82 1.75
#   1.7  1.66 1.63 1.59 1.53 1.47 1.48]]
```

This problem is somewhat obscured in the output, because the averaging kernel is interpolated to the CMAQ levels. The masked values are treated as zeros, so the interpolated output has multiple unmasked values -- like shown below

```
Interpolated = [
    0.22, 0.22, 0.18, 0.11, 0.02, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
    0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
    0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0
]
```

Averaging Kernel Appendix
-------------------------

Further description of the averaging kernel concept here.

* Vertical Column Density as a sum of partials : _V_ = \sum_z _V_z_
* Slant Column Density as a sum of partials : _S_ = \sum_z _S_z_
* Relating Slant and Vertical Partial Columns : _S_z_ = _V_z_ * _w_z_
* Calculating an Air Mass Factor (_M_) with a Prior Vertical Column (_P_z_) : _M_ = \sum_z _P_z_ * _w_z_
* Using this approximation : _V_ = _S_ / _M_

The satellite measures _S_ and calculates _M_ using a model prior _P_z_, so the satellite _V_ = _S_ / _M_ or:

_V_ = 1/_M_ * \sum_z _V_z_ * _w_z_

This leads to the definition of an averaging kernel: _K_z_ = _w_z_ / _M_

So that the model vertical column using the satellite prior is defined as 

_V_ = \sum_z _K_z_ * _V_z_

**Comment by chogrefe** [comment]
Thanks for documenting this. 

I'll note that I obtained the syntax used in my scripts (`AKKEY="ScatteringWeight[:]/AmfTrop[:]"`) from the [convercmaq.sh script in the repo](https://github.com/barronh/cmaqsatproc/blob/master/convertcmaq.sh), so this script should probably be updated. When updating it, the name of the variable `ScatteringWeight` should also be changed to `ScatWgt` to match the name in the file produced by convertsat.sh

**Comment by barronh** [comment]
You’re right! During development, the AMF was being duplicated in all layers, so it would have worked. I’ll update the docs.

**Comment by barronh** [comment]
This comment refers to the old system. As of v2, it is not relevant.
