### ISSUE TITLE
How to input local files?

### ISSUE THREAD

**Issue by gc13141112** [barronh/cmaqsatproc#8]
Hi, Barronh,
I have a question. How do I use the tool to process tropomi data from the local disk? The tropomi data are as follows:
S5P_RPRO_L2__NO2____20220630T232430_20220701T010600_24425_03_020400_20230203T013856.SUB.nc4
S5P_RPRO_L2__NO2____20220701T010600_20220701T024730_24426_03_020400_20230203T014616.SUB.nc4
Thanks in advance for your help!

Chao

**Comment by gc13141112** [comment]
I solve it. Thx

**Comment by barronh** [comment]
The answer is to use the `paths_to_level3` method of the satellite reader.
