### ISSUE TITLE
Multiple Versions used by default

### ISSUE THREAD

**Issue by barronh** [barronh/cmaqsatproc#9]
Thanks to @tnskipper for raising this issue. He noticed that processing TropOMI HCHO during 2019 used both version 1 and version 2 products.

## Intro

By default, `cmaqsatproc` uses `short_name` to query for data paths, which is not perfectly unique. A great example is the formaldehyde product `S5P_L2__HCHO___HiR`, which has two versions (`S5P_L2__HCHO___HiR.1` and `S5P_L2__HCHO___HiR.2`) that overlap temporally (2019-08-06 to 2020-07-13 and 2018-04-30 ongoing). Because they temporally overlap for all of v1, a standard query based on `short_name` from 2019-06-06 to 2020-01-13 will use both version 1 and 2.

In this specific case, it seems clear that version 2 should supersede version 1. I could change the TropOMIHCHO reader to be more specific. If two products did not overlap, a long-term query might ideally include both. Which leaves the question, how specific should the default system be.

## A few pieces of context:

* a custom L3 file always says which files were used in it in the description attribute, so you can always see what was included.
* you can always provide more common metadata repository keywords (eg, concept_id, version, etc), so you have the option to limit what is used.
* You can even do custom parsing of links by separately calling `cmr_links`, removing links you don't want and passing those links to `paths_to_level3` because `paths_to_level3` works with both local paths and remote urls.

## Deeper Dive into Problem and Solution

The problem is rooted in the `cmr_links` method, which is used by `cmr_to_level3` to get the links. Reproducing the issue with `cmr_links` is fast and easy. The query below returns six urls including both version 1 and 2.

```
import cmaqsatproc as csp

satreader = csp.reader_dict['TropOMIHCHO']
links = satreader.cmr_links(
    bbox=(-97, 40, -65, 60),
   temporal=f'2019-09-19T00:00:00Z/2019-09-19T23:59:59Z'
)
print('\n'.join(links))

# Outputs:
# https://tropomi.gesdisc.eosdis.nasa.gov/opendap/S5P_TROPOMI_Level2/S5P_L2__HCHO___HiR.1/2019/262/S5P_OFFL_L2__HCHO___20190919T152238_20190919T170408_10020_01_010107_20190925T173647.nc
# https://tropomi.gesdisc.eosdis.nasa.gov/opendap/S5P_TROPOMI_Level2/S5P_L2__HCHO___HiR.1/2019/262/S5P_OFFL_L2__HCHO___20190919T170408_20190919T184537_10021_01_010107_20190925T192023.nc
# https://tropomi.gesdisc.eosdis.nasa.gov/opendap/S5P_TROPOMI_Level2/S5P_L2__HCHO___HiR.1/2019/262/S5P_OFFL_L2__HCHO___20190919T184537_20190919T202707_10022_01_010107_20190925T212319.nc
# https://tropomi.gesdisc.eosdis.nasa.gov/opendap/S5P_TROPOMI_Level2/S5P_L2__HCHO___HiR.2/2019/262/S5P_RPRO_L2__HCHO___20190919T152238_20190919T170408_10020_03_020401_20230126T014841.nc
# https://tropomi.gesdisc.eosdis.nasa.gov/opendap/S5P_TROPOMI_Level2/S5P_L2__HCHO___HiR.2/2019/262/S5P_RPRO_L2__HCHO___20190919T170408_20190919T184537_10021_03_020401_20230126T014916.nc
# https://tropomi.gesdisc.eosdis.nasa.gov/opendap/S5P_TROPOMI_Level2/S5P_L2__HCHO___HiR.2/2019/262/S5P_RPRO_L2__HCHO___20190919T184537_20190919T202707_10022_03_020401_20230126T014919.nc
```

This can be solved by adding the version keyword.

```
import cmaqsatproc as csp

satreader = csp.reader_dict['TropOMIHCHO']
links = satreader.cmr_links(
    version='2', bbox=(-97, 40, -65, 60),
    temporal=f'2019-09-19T00:00:00Z/2019-09-19T23:59:59Z'
)
print('\n'.join(links))
# Outputs:
# https://tropomi.gesdisc.eosdis.nasa.gov/opendap/S5P_TROPOMI_Level2/S5P_L2__HCHO___HiR.2/2019/262/S5P_RPRO_L2__HCHO___20190919T152238_20190919T170408_10020_03_020401_20230126T014841.nc
# https://tropomi.gesdisc.eosdis.nasa.gov/opendap/S5P_TROPOMI_Level2/S5P_L2__HCHO___HiR.2/2019/262/S5P_RPRO_L2__HCHO___20190919T170408_20190919T184537_10021_03_020401_20230126T014916.nc
# https://tropomi.gesdisc.eosdis.nasa.gov/opendap/S5P_TROPOMI_Level2/S5P_L2__HCHO___HiR.2/2019/262/S5P_RPRO_L2__HCHO___20190919T184537_20190919T202707_10022_03_020401_20230126T014919.nc
```

Or by adding concept_id:

```
import cmaqsatproc as csp

satreader = csp.reader_dict['TropOMIHCHO']
links = satreader.cmr_links(
    concept_id='C1918210023-GES_DISC', bbox=(-97, 40, -65, 60),
    temporal=f'2019-09-19T00:00:00Z/2019-09-19T23:59:59Z'
)
print('\n'.join(links))
# Outputs:
# https://tropomi.gesdisc.eosdis.nasa.gov/opendap/S5P_TROPOMI_Level2/S5P_L2__HCHO___HiR.2/2019/262/S5P_RPRO_L2__HCHO___20190919T152238_20190919T170408_10020_03_020401_20230126T014841.nc
# https://tropomi.gesdisc.eosdis.nasa.gov/opendap/S5P_TROPOMI_Level2/S5P_L2__HCHO___HiR.2/2019/262/S5P_RPRO_L2__HCHO___20190919T170408_20190919T184537_10021_03_020401_20230126T014916.nc
# https://tropomi.gesdisc.eosdis.nasa.gov/opendap/S5P_TROPOMI_Level2/S5P_L2__HCHO___HiR.2/2019/262/S5P_RPRO_L2__HCHO___20190919T184537_20190919T202707_10022_03_020401_20230126T014919.nc
```

To use these additional options with `cmr_to_level3`, use the `link_kwargs`. For example:

```
import cmaqsatproc as csp

cg = csp.open_griddesc('12US1')
satreader = csp.reader_dict['TropOMIHCHO']
l3 = satreader.cmr_to_level3(
    bbox=(-97, 40, -65, 60), temporal=f'2019-09-19T00:00:00Z/2019-09-19T23:59:59Z',
    grid=cg.csp.geodf, link_kwargs=dict(concept_id='C1918210023-GES_DISC')
)
l3.to_netcdf('outpath.nc')
```

To use a custom subset of links:

```
import cmaqsatproc as csp

cg = csp.open_griddesc('12US1')
satreader = csp.reader_dict['TropOMIHCHO']
links = satreader.cmr_links(
    bbox=(-97, 40, -65, 60), temporal=f'2019-09-19T00:00:00Z/2019-09-19T23:59:59Z',
)
links = [l for l in links if 'HiR.2' in l]
print('\n'.join(links))
# Outputs
# https://tropomi.gesdisc.eosdis.nasa.gov/opendap/S5P_TROPOMI_Level2/S5P_L2__HCHO___HiR.2/2019/262/S5P_RPRO_L2__HCHO___20190919T152238_20190919T170408_10020_03_020401_20230126T014841.nc
# https://tropomi.gesdisc.eosdis.nasa.gov/opendap/S5P_TROPOMI_Level2/S5P_L2__HCHO___HiR.2/2019/262/S5P_RPRO_L2__HCHO___20190919T170408_20190919T184537_10021_03_020401_20230126T014916.nc
# https://tropomi.gesdisc.eosdis.nasa.gov/opendap/S5P_TROPOMI_Level2/S5P_L2__HCHO___HiR.2/2019/262/S5P_RPRO_L2__HCHO___20190919T184537_20190919T202707_10022_03_020401_20230126T014919.nc

l3 = satreader.paths_to_level3(links, grid=cg.csp.geodf)
l3.to_netcdf('outpath.nc')
```

**Comment by tnskipper** [comment]
Thanks for the details. Using `link_kwargs` to specify the `short_name` and `version` in `cmr_to_level3` solves my issue. 

I will add a couple of details that you may already be aware of.

Reprocessed HiR.2 data is available going back to the start of TROPOMI data coverage which means there is also overlap between the HiR.2 and (non-HiR) v1 products from the start date of TROPOMI data to 2019-08-06 (when HiR.1 data became available). Including the following in `cmr_to_level3` works for me to get HiR.2 regardless of the date:
`link_kwargs=dict(short_name='S5P_L2__HCHO___HiR', version='2')` 

It looks like the reprocessing to HiR.2 has been done for all TROPOMI products, so this will affect other products in addition to formaldehyde.

**Comment by barronh** [comment]
Maybe it should default to v2 unless specified.

**Comment by barronh** [comment]
I'm have an edit to switch all short_name values to concept_id. I'm also going to add warnings when only short_names are used and document how to get a concept_id from a short_name. I am somewhat worried that this will require more constant updating. But I suppose a worry is better than an existing problem... I'll set up a PR and ask that you review it.

**Comment by barronh** [comment]
@tnskipper Oops. I pushed to the main branch instead of a PR. Can you test?

**Comment by tnskipper** [comment]
The update looks good to me. It solves the issue that multiple versions of TROPOMI L2 files can be returned by default. Below is a summary of my testing.

I tested the updated version by generating an L3 TROPOMI HCHO file for a date with overlapping coverage of HiRv1 and HiRv2 with the `cmr_to_level3` method using the default values (i.e., I did not pass any `link_kwargs` to `cmr_to_level3`). This uses HiRv2 L2 files by default as intended. I compared this L3 file to one that I had previously generated by downloading HiRv2 L2 files then creating the L3 file with the `paths_to_level3` method, and the `formaldehyde_tropospheric_vertical_column` from the two L3 files are identical.

I am less familiar with the products other than the TROPOMI products, but for the satellite readers that were updated to use `concept_id`, I checked with `cmr_links` to verify that a valid list of links was returned. Everything except OMPROFOZ returned a valid list of links (and I see a comment in the code that OMPROFOZ may not actually be accessible this way, so this is probably expected for OMPROFOZ).

I will note two minor things that you can consider if you want.
1. In the docstrings of `cmr_links` for the TROPOMI readers it says "HiR v2 starts 2019-08-06T02:41:41.000Z" which is technically not true. The start date of the reprocessed HiRv2 data goes back to ~20180501 with some slight variation for different products. For the products that are currently supported, the HiRv2 start dates are 20180501 for NO2, 20180507 HCHO, and 20180430 for CO and CH4 according to the GES DISC entries.

2. I was not able to figure out how to trigger the warning for using only a `short_name` for TROPOMI. However, I can still return overlapping HiRv1 and HiRv2 links using the code below without triggering the warning. If I instead do not specify `concept_id` then it does default to the HiRv2 files as intended. This may be a case that you want the warning to handle or maybe not.
```
GDNAM = '12US1'
date = '2019-09-01'
readername = 'TropOMIHCHO'
cg = csp.open_griddesc(GDNAM)
satreader = csp.reader_dict[readername]

links = satreader.cmr_links(
    temporal=f'{date}T00:00:00Z/{date}T23:59:59Z',
    bbox=cg.csp.bbox(),
    short_name='S5P_L2__HCHO___HiR',
    concept_id=None
)
```

**Comment by barronh** [comment]
1. I've updated the doc strings to show the actual date that I get for each TropOMI product (2x Apr 30, May 1, and May 7). 
2. I love that you were able to force it! I hadn't even thought about someone passing `concept_id=None`. Nor had I thought that the `requests.get` command would correctly remove the parameters explicitly assigned None! Honestly, I'm glad it works! I have changed the warning so that if concept_id is missing OR is None, it will warn. 
3. The warning can also be accessed using the getcmrlinks function directly. Below is an example.

```
>>> import cmaqsatproc as csp
>>> links = csp.utils.getcmrlinks(short_name='S5P_L2__CO____', temporal='2018-04-01T00:00:00/2018-05-01T00:00:00')
/home/bhenders/devel/cmaqsatproc/cmaqsatproc/utils.py:98: UserWarning: short_name not guaranteed unique. Try the concept_id keyword instead of short_name. Potential values for concept_id can  be found at: https://cmr.earthdata.nasa.gov/search/collections?short_name=S5P_L2__CO____
  warnings.warn(msg)
```


I pushed the updates to main.

**Comment by tnskipper** [comment]
I will confirm that I am now getting the warning when `concept_id=None`. Thanks for the updates!
